version: "3"

services:
    shell:
        build:
            context: ./dev/
        volumes:
            - type: bind
              source: ./
              target: /data
        stdin_open: true
        tty: true
        entrypoint: /bin/bash

    execute:
        build:
            context: ./dev/
        volumes:
            - type: bind
              source: ./
              target: /data
        stdin_open: true
        tty: true
        entrypoint: /data/dev/entrypoint
