#!/usr/bin/env bash
# file: entrypoint

# shellcheck disable=SC2312 # Consider invoking this command separately to avoid masking its return value (or use '|| true' to ignore).


__FILE__="$(readlink -f "${BASH_SOURCE[0]}")"
__DIR__="$(dirname "${__FILE__}")"
__PWD__="$(pwd)"
DIR_PROJ="$(readlink -f "${__DIR__}/..")"
DIR_SRC="${DIR_PROJ}/src"
DIR_TESTS="${DIR_PROJ}/tests"

function env_vars {
    echo " -= Environment Variables =-"
    echo " __FILE__: ${__FILE__}"
    echo "  __DIR__: ${__DIR__}"
    echo "  __PWD__: ${__PWD__}"
    echo " DIR_PROJ: ${DIR_PROJ}"
    echo "  DIR_SRC: ${DIR_SRC}"
    echo "DIR_TESTS: ${DIR_TESTS}"
}

function unit-tests {
    # Change to directory with `.shunit2rc` file
    if ! cd "${DIR_PROJ}"; then
        printf "\x1b[91mFatal error:\x1b[31m could not change directory\x1b[0m" > /dev/stderr
        exit 1
    fi

    "${DIR_TESTS}/shunit2sl" "$@"
}

function coverage {
    # Change to directory with `.simplecov` and `.shunit2rc` files
    if ! cd "${DIR_PROJ}"; then
        printf "\x1b[91mFatal error:\x1b[31m could not change directory\x1b[0m" > /dev/stderr
        exit 1
    fi

    bashcov --skip-uncovered -- "${DIR_TESTS}/shunit2sl" "$@"
}

function shellchecks {
    # Change to directory with `.shellcheckrc` file
    if ! cd "${DIR_PROJ}"; then
        printf "\x1b[91mFatal error:\x1b[31m could not change directory\x1b[0m" > /dev/stderr
        exit 1
    fi

    shellcheck \
        "${DIR_SRC}"/bash-util-lib.sh \
        "${DIR_SRC}"/bash-util-lib.*.sh \
        "${DIR_TESTS}"/bash-util-lib.test.sh \
        "${DIR_TESTS}"/bash-util-lib.*.test.sh \
        "${DIR_TESTS}"/shunit2.*
}

# @description Update library version and date variables
# @param VERSION - [Optional] Version to use to replace current version (Format: #.#.#[-tag])
function update-version {
    local VERSION="$1"
    local FILENAME VERSION_DATE

    # shellcheck source=../src/bash-util-lib.ansi.const.sh
    source "${DIR_SRC}/bash-util-lib.ansi.const.sh"

    FILENAME="bash-util-lib.*.sh"

    if [[ -z "${VERSION}" ]]; then
        printf '%b' "${ANSI_BOLD}Format:  ${ANSI_RESET}${ANSI_YELLOW}[0-9]+.[0-9]+.[0-9]+[-(a-z0-9_)]*${ANSI_RESET}\n"
        printf '%b' "${ANSI_BOLD}Example: ${ANSI_RESET}${ANSI_YELLOW}${ANSI_ITALIC}1.2.3-alpha${ANSI_RESET}\n"
        printf '%b' "${ANSI_CYAN}Update version value ${ANSI_ITALIC}[EMPTY Cancels]${ANSI_ITALIC_RESET}:${ANSI_RESET} "
        read -r VERSION
    fi

    if [[ -n "${VERSION}" ]]; then
        if sed -i "s/BASH_UTIL_LIB_VERSION=\".*\"$/BASH_UTIL_LIB_VERSION=\"${VERSION}\"/" "${DIR_SRC}"/${FILENAME}; then
            printf '%b' "${ANSI_GREEN}Successfully updated version to ${ANSI_BOLD}${ANSI_BRIGHT_GREEN}${VERSION}${ANSI_BOLD_RESET}${ANSI_GREEN}.${ANSI_RESET}\n"

            VERSION_DATE="$(date '+%F %R:%S')"

            if sed -i "s/BASH_UTIL_LIB_DATE=\".*\"$/BASH_UTIL_LIB_DATE=\"${VERSION_DATE}\"/" "${DIR_SRC}"/${FILENAME}; then
                printf '%b' "${ANSI_GREEN}Version Date updated: ${ANSI_BOLD}${ANSI_BRIGHT_GREEN}${VERSION_DATE}${ANSI_RESET}\n"
            fi
        else
            printf '%b' "${ANSI_RED}Failed to update version.${ANSI_RESET}\n"
        fi
    fi
}


if [[ "$#" -eq 0 ]]; then
    # No arguments provided
    bash
elif declare -F | awk '{print $3}' | grep -q "^$1$"; then
    # First provided argument is name of defined function
    "$@"
else
    # First provided argument is not name of defined function
    exec "$@"
fi
